# Site settings
title: Arctic Fox
email: 
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo
baseurl: # the subpath of your site, e.g. /blog/
url: "http://diezcami.github.io" # the base hostname & protocol for your site
twitter_username: username
github_username: username