# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Jonathan New"
description:        "A blog on tech and other miscellany"


url:                "blog.jonnew.com"
author:             "newtang"
twitter:
  username:         "newtang"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
#  - name:           "About"
#    href:           "//blog.jonnew.com/about"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"